# Dependabot Configuration
# https://docs.github.com/code-security/supply-chain-security/configuration-options-for-dependency-updates
#
# FIXME: v2 doesn't support auto-merge.  See:
# https://github.com/dependabot/dependabot-core/issues/1823#issuecomment-641594279
# https://github.com/dependabot/dependabot-core/issues/1973#issuecomment-640918321
# https://github.com/dependabot/dependabot-core/issues/2268
# Consider bot:
# https://kodiakhq.com/docs/prior-art-and-alternatives
# Consider GH action:
# https://github.com/dependabot/dependabot-core/issues/2268#issuecomment-654608325
# Must use on: workflow_run or on: pull_request_target to work around
# https://github.com/dependabot/dependabot-core/issues/2268#issuecomment-794745837
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
